# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OpenDataRSS
                                 A QGIS plugin
 This plugin uses open data RSS feeds that contain data with georeferenced coordinates to generate and display a feature with the data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-11-19
        copyright            : (C) 2018 by Dennis Sherman; Sherman Geospatial
        email                : dennis.sherman@shermangeospatial.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load OpenDataRSS class from file OpenDataRSS.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .open_RSS import OpenDataRSS
    return OpenDataRSS(iface)
